/* eslint-disable */
/**
 * Generated by Convex (stub for type-checking before `convex dev` is run).
 * This file will be overwritten by `convex dev` or `convex codegen`.
 */

// biome-ignore lint/suspicious/noExplicitAny: stub file for generated Convex types
export const api: any = {};
// biome-ignore lint/suspicious/noExplicitAny: stub file for generated Convex types
export const internal: any = {};
// biome-ignore lint/suspicious/noExplicitAny: stub file for generated Convex types
export const components: any = {};
